version: '3'

services:
  db:
    image: postgres:9.5
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
  scalelite-api:
    image: blindsidenetwks/scalelite:v1.0.4-api
    container_name: scalelite-api
    restart: unless-stopped
    env_file: scalelite
    depends_on:
      - db
      - redis
  scalelite-nginx:
    image: blindsidenetwks/scalelite:v1.0.4-nginx
    restart: unless-stopped
    container_name: scalelite-nginx
    env_file: scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
    ports:
      - "80:80"
      - "443:443"
  scalelite-poller:
    image: blindsidenetwks/scalelite:v1.0.4-poller
    container_name: scalelite-poller
    restart: unless-stopped
    env_file: scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
  scalelite-recording-importer:
    image: blindsidenetwks/scalelite:v1.0.4-recording-importer
    container_name: scalelite-recording-importer
    restart: unless-stopped
    env_file: scalelite
    depends_on:
      - scalelite-api
      - db
      - redis
