version: '3'

services:
  db:
    image: postgres:9.5
    restart: unless-stopped
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    restart: unless-stopped
  scalelite-api:
    image: blindsidenetwks/scalelite:v1.0.4-api
    container_name: scalelite-api
    restart: unless-stopped
    env_file: scalelite
    depends_on:
      - db
      - redis
